const LINE1 = 'Generated by adevtool; do not edit'
const LINE2 = 'For more info, see https://github.com/kdrag0n/adevtool'

export const MAKEFILE_HEADER = `# ${LINE1}
# ${LINE2}`

export const SOONG_HEADER = `// ${LINE1}
// ${LINE2}`

export const XML_HEADER = `<!-- ${LINE1}
     ${LINE2} -->`
